#!/bin/bash
# SumiNami Bar - Theme colors for scripts
# Auto-generated for: kanagawa
# DO NOT EDIT - regenerated by generate-style

# Theme info
THEME_NAME="kanagawa"
THEME_IS_LIGHT="true"

# Background colors
COLOR_BG="#16161D"
COLOR_BG_LIGHT="#1F1F28"
COLOR_BORDER="#363646"

# Foreground colors
COLOR_FG="#DCD7BA"
COLOR_MUTED="#727169"

# Accent colors (WCAG compliant)
COLOR_ACCENT="#D27E99"
COLOR_SYSTEM="#98BB6C"
COLOR_WEATHER="#A3D4D5"
COLOR_NETWORK="#957FB8"
COLOR_AUDIO="#7FB4CA"
COLOR_HIGHLIGHT="#7FB4CA"

# State colors
COLOR_WARNING="#E6C384"
COLOR_CRITICAL="#E46876"
